[package]

name = "peg"
version = "0.3.16"
authors = [ "Kevin Mehall <km@kevinmehall.net>" ]
license = "MIT"
repository = "https://github.com/kevinmehall/rust-peg"
description = """
A parser generator built on the Parsing Expression Grammar (PEG) formalism.
"""

[dependencies]
quote = "0.3"

[[bin]]
name = "peg"
path = "src/peg.rs"
test = false
bench = false

[lib]
plugin = true
name = "peg_syntax_ext"

[features]
trace = []
